### ISSUE TITLE
Monitor repos with Dependabot

### ISSUE THREAD

**Issue by davidcmoulton** [libero/libero#125]
## Problem / Motivation
As a Libero Publisher developer, I want to have confidence that all known dependency vulnerabilities are identified so I can keep the codebase secure.

## Proposed solution
Implement [Dependabot](https://dependabot.com/) for all repos that use dependencies.

## Tasks
Add Dependabot to each of these repos:
- [ ] https://github.com/libero/search
- [ ] https://github.com/libero/browser
- [ ] https://github.com/libero/pattern-library
- [ ] https://github.com/libero/sample-configuration
- [ ] https://github.com/libero/jats-support
- [ ] https://github.com/libero/content-store
- [ ] https://github.com/libero/php-coding-standard
- [ ] https://github.com/libero/xml-validator
- [ ] https://github.com/libero/content-api-bundle
- [ ] https://github.com/libero/api-problem-bundle
- [ ] https://github.com/libero/schemas
- [ ] https://github.com/libero/pattern-library-config-manager
- [ ] https://github.com/libero/content-negotiation-bundle
- [ ] https://github.com/libero/ping-controller
- [ ] https://github.com/libero/dummy-api

## Clarification needed and assumptions
- What level (if any) of automatic merge should be allowed?
- What frequency of updates should be configured?
- Can we manage it with configuration as code?

**Comment by giorgiosironi** [comment]
Noting this has been partially implemented for selected repositories and technologies, e.g. updating the `scripts` Git submodule in the services that use it to reuse Travis CI scripts.
