### ISSUE TITLE
Write file API spec

### ISSUE THREAD

**Issue by giorgiosironi** [libero/libero#127]
Write the specification for a Libero API file store, that can receive files and return a URI for them to be accessible through a browser.

## Tasks

- [ ] Create specification document
- [ ] Add conventions
- [ ] Add endpoints
  - [ ] Allowed methods
  - [ ] Allowed response codes
  - [ ] Sample requests/responses pairs
- [ ] Create schema

## Links

- Existing similar specs:
  - [Content API](https://docs.google.com/document/d/1jMJ4NxzHiBroNerUbiNWn5H01kgaPRvfRELr1WDvPRY/edit)
  - [Search API](https://docs.google.com/document/d/1MTFlgZjM6wk507j9NPiQuGSco7li1sOVj9SLAeGqbFI/edit)
- [Schemas](https://github.com/libero/schemas)

## Related

- Blocks #133 (implementation).

**Comment by giorgiosironi** [comment]
Not sure if there is an equivalent `read` version of this issue, whose conventions should be followed by https://github.com/libero/libero/issues/130

**Comment by thewilkybarkid** [comment]
As in being able to read what's in the store (as opposed to being able to access the actual file)? No plans so far...

**Comment by thewilkybarkid** [comment]
Tempted to drop this idea for now, in favour of using a [filesystem abstraction](https://flysystem.thephpleague.com/docs/) and something like https://github.com/illuminate/filesystem/blob/aaefd9cbc59767a448d28b4bdbf7b67c6b5ba925/FilesystemAdapter.php#L389-L410. Far simpler to implement (ie no service in the middle); and can still introduce it when we have a strong use case.

**Comment by giorgiosironi** [comment]
The scope of this is to download files from an external source and store them to make them publicly accessible to a browser; if the `content-store` can do that on its own without other services (even with multiple backends), good for me.
