### ISSUE TITLE
Display content images

### ISSUE THREAD

**Issue by thewilkybarkid** [libero/libero#128]
Show images without any visible metadata/style:

<img width="759" alt="Screenshot 2019-04-01 at 11 32 39" src="https://user-images.githubusercontent.com/1784740/55321559-e1edb380-5471-11e9-9fa2-fcb94c2571b1.png">

## Tasks

- [x] Create pattern (https://github.com/libero/pattern-library/pull/82)
  - [x] Supports multiple formats
  - [x] Supports multiple sizes
  - [x] Supports `alt`
- [x] Add to Browser (https://github.com/libero/browser/pull/73)
  - [x] Pattern implemented
  - [x] Sample images available in the dummy content

## Related

- Followed by #129 (add title and caption), and #135 (style images).
- #130 will define JATS to use in Browser.
