### ISSUE TITLE
Add image titles/captions

### ISSUE THREAD

**Issue by thewilkybarkid** [libero/libero#129]
Add titles and captions to images (both optional).

<img width="685" alt="Screenshot 2019-04-03 at 09 25 12" src="https://user-images.githubusercontent.com/1784740/55464194-6ff0a800-55f2-11e9-8f6c-79c3080c6f18.png">

## Tasks

- [x] Create pattern (https://github.com/libero/pattern-library/pull/84)
  - [x] Title
  - [x] Caption
- [x] Add JATS support (https://github.com/libero/jats-support/pull/12)
- [x] Add to Browser (https://github.com/libero/browser/pull/77)
  - [x] Title
    - [x] Pattern implemented
    - [x] Sample titles added to dummy content
  - [x] Caption
    - [x] Pattern implemented
    - [x] Sample captions added to dummy content

## Notes

- Deliberately doesn't include 'Figure 1'-style labels.

## Related

- Blocked by #128.
- Followed by #135 (style images).
- #130 will define JATS to use in Browser.
