### ISSUE TITLE
Add sample images to the unstable environment

### ISSUE THREAD

**Issue by thewilkybarkid** [libero/libero#130]
Add sample images to content in the unstable environment.

## Tasks

- [x] Define JATS to support. (https://github.com/libero/jats-support/pull/11)
- [x] Add to the unstable environment
  - ~[ ] Run Nginx container.~
  - ~[ ] Serve image files.~
  - [x] Add images to JATS content. (https://github.com/libero/sample-configuration/pull/31)

## Related

- #128 will see images displayed in Browser.
- #129 will see title and captions displayed in Browser.

**Comment by giorgiosironi** [comment]
Can probably still code-name this service `file-store_nginx` or similar, since it fulfills that role.

**Comment by thewilkybarkid** [comment]
Proposed JATS starting point for https://github.com/libero/libero/issues/128 and https://github.com/libero/libero/issues/129:

```xml
<fig xml:base="[base-uri]">
    <caption>
        <title>[text]</title>
        <p>[text]</p>
    </caption>
    <graphic xlink:href="[uri]" mime-subtype="[web format]" mimetype="image"/>
</fig>
```

- `<caption>` is optional, as are its children.
- `@xml:base` not required if the `@xlink:href` is absolute.
- `@mimetype`/`mime-subtype` not required if `@xlink:href` has a known file extension (eg `xlink:href="some-image.jpg"`.
- other `<graphic>` are ignored, and the whole `<fig>` is if they all are.
- assumes that TIFFs etc are already converted to a web format.

/cc @Melissa37

**Comment by giorgiosironi** [comment]
Drafting a `sample-configuration` change to add the nginx container stubbing `file-store`.

**Comment by giorgiosironi** [comment]
https://github.com/libero/sample-configuration/pull/29
