### ISSUE TITLE
Add PUT support to the content store

### ISSUE THREAD

**Issue by thewilkybarkid** [libero/libero#132]
Make the content store writeable.

## Tasks

- [x] Handles `PUT` requests (https://github.com/libero/content-api-bundle/pull/22, https://github.com/libero/content-store/pull/7)
- [x] Validate input (basics, not full schema)
- [x] Send assets to a ~file store~ publicly-accesible filesystem and rewrite their paths (https://github.com/libero/content-store/pull/9)
- [x] Unstable environment updated

## Notes

- Can be done synchronously for now.

## Links

- [Content API specification](https://docs.google.com/document/d/1jMJ4NxzHiBroNerUbiNWn5H01kgaPRvfRELr1WDvPRY/edit)
- [Base schema](https://github.com/libero/schemas/blob/master/api/content/item.rng)

## Related

- ~#127 (file API spec)~
- #131 (eLife-style adapter that will send requests)

**Comment by giorgiosironi** [comment]
Minimal process to be implemented:

1. The content store validates the Libero-wrapped JATS according to the configured RelaxNG schema
1. The content store downloads each of the JPEG images
1. The content store performs a PUT request for each of the JPEG to the object store
1. The object store persists the images in a publicly available location like an S3 bucket (not a responsibility of this ticket, but for clarity)
1. The content store replaces the references to images in the Libero-wrapped JATS with the URLs returned by the object store, if possible with the xml:base attribute
1. The content store persists the Libero-wrapped JATS into its database

**Comment by thewilkybarkid** [comment]
> 2. The content store downloads each of the JPEG images
> 3. The content store performs a PUT request for each of the JPEG to the object store

Could be that the content sends the URI to the object store, which then downloads it.
