### ISSUE TITLE
Add a database to the Content Store

### ISSUE THREAD

**Issue by thewilkybarkid** [libero/libero#134]
Currently it uses the filesystem. This was initially done as it's only serving static content, but in #132 it will become writable.

## Tasks

- [x] Add PostgreSQL to the dev environment (https://github.com/libero/content-store/pull/8)
  - [x] Use database migrations
- [x] Add PostgreSQL to the unstable environment (https://github.com/libero/sample-configuration/pull/33)
  - [x] Use database migrations

## Related

- #132 makes it writeable.

**Comment by giorgiosironi** [comment]
Should be easy to carry over the `postgres` container from the development environment to `sample-configuration`. Should mount a volume to persist data on the host.

**Comment by giorgiosironi** [comment]
Couple of preparations for data persistence, that fix a current issue with `search`:
- https://github.com/libero/sample-configuration/pull/32
- https://github.com/libero/environments/pull/25

**Comment by giorgiosironi** [comment]
Since there is preparatory work on this, moving to `Doing`.

**Comment by giorgiosironi** [comment]
Preparatory work on volumes initialization rolled out, will be replicated for `content-store_postgres` or a similar container.
