### ISSUE TITLE
Create listing grid

### ISSUE THREAD

**Issue by thewilkybarkid** [libero/libero#136]
## Tasks

- [x] Create pattern (https://github.com/libero/pattern-library/pull/78)
  - [x] Two columns
  - [x] Handles only one column
  - [x] Responsive
- [x] Implemented in Browser (https://github.com/libero/browser/pull/69)
