### ISSUE TITLE
Add header with logo

### ISSUE THREAD

**Issue by thewilkybarkid** [libero/libero#139]
Add a (site) header pattern that contains just a logo.

<img width="1433" alt="Screenshot 2019-04-17 at 08 32 49" src="https://user-images.githubusercontent.com/1784740/56269506-b6aec980-60eb-11e9-8e72-f8a1dc9ca681.png">

## Tasks

- [x] Add (site) header pattern
  - [x] Contains optional logo
  - [x] Libero logo used by default
  - [x] Revise layout
- [x] Add to Browser
  - ~[ ] Logo can be set~

## Notes

- To be used in the `start` area of the `page-grid`.
- I'm not separating the template and styles.
- eLife use different images at different sizes:
  Desktop/tablet: <img width="144" alt="Screenshot 2019-04-17 at 08 35 37" src="https://user-images.githubusercontent.com/1784740/56269615-f675b100-60eb-11e9-8dae-6b38898a4236.png"> Mobile: <img width="39" alt="Screenshot 2019-04-17 at 08 35 44" src="https://user-images.githubusercontent.com/1784740/56269620-f83f7480-60eb-11e9-99ef-e61b13dab303.png">
  Assuming this isn't supported (the logo is a single image).

## Related

- Followed by #140 (add menu).
- Followed by #163 (allow custom logos).

**Comment by thewilkybarkid** [comment]
Libero logo:

```svg
<svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 112 144"><defs><style>.cls-1{fill:#9fa0a4;}.cls-2{fill:#0a9dd9;}.cls-3{fill:#1757a2;}</style></defs><title>libero-logo</title><rect class="cls-1" y="128" width="48" height="16"/><circle class="cls-2" cx="104" cy="8" r="8"/><polygon class="cls-3" points="48 112 0 112 0 0 16 0 16 96 48 96 48 112"/><rect class="cls-2" x="96" y="32" width="16" height="48"/></svg>
```

**Comment by davidcmoulton** [comment]
Pattern library PR: https://github.com/libero/pattern-library/pull/97

**Comment by thewilkybarkid** [comment]
The pattern PR has been merged but doesn’t seem to match the indented (desktop) style. Was that intentional?

Had a look at the designs and they’re inconsistent, so not sure what spacing/size is meant either. /cc @chugginselifesciences

**Comment by chugginselifesciences** [comment]
Thanks @thewilkybarkid. You're right the header looks quite small/not tall enough.

_After talking with @davidcmoulton the following should help. Below 730px to come_ 

The idea is more or less that the header is "the same height" as the eLife journal header but instead of two rows to it, there is one with the content/menu centered.

For screen widths 730px and above, I had hoped for:

- The header 'fixed' at 96px tall (including the 1px divider) - defined by max-height in journal I think
- The left edge/position of the logo should be defined by the grid.
- There is 8px padding top and bottom in the header (or 7px at bottom not including the 1px divider)
_The 8px padding is based on the eLife journal site and makes sense to me to prepare ahead for the 2nd row of menus/split header._  
- A container for the logo would therefore be 70px tall. _I think it makes sense to add some padding to this to prevent other journal logos filling the entire available space_
- The libero logo should be 28px wide x 36px tall - so 22px top and bottom padding within the 70px container
- The width is defined by the logo, and the container should be 36px from the "menu divider", which is a 1x24px light grey line. This isn't needed yet but if planning ahead should be 36px from the logo and 36px from the menu items.


![image](https://user-images.githubusercontent.com/41907215/58329837-68e55980-7e2d-11e9-969e-71d8dbd4689d.png)

Same for IJM with different logo padding:

![image](https://user-images.githubusercontent.com/41907215/58330152-2d975a80-7e2e-11e9-876a-b3ab354e1b3e.png)

**Comment by chugginselifesciences** [comment]
Below 730px the following should apply:

- 8px padding remains
- 18px from left edge
- But height of header reduces to 60px (59px not including 1px divider)
- Logo reduces to 18px by 24px
- Padding around Libero logo would reduce to 10px top and bottom
- Right padding between logo and menu divider (and padding of menu) reduces to 18px




![image](https://user-images.githubusercontent.com/41907215/58330692-6257e180-7e2f-11e9-94a2-110e54406570.png)

And with IJM logo at 32px by 32px (with 6px padding above and below) - still 18px from left edge, and divider 18px from logo etc.

![image](https://user-images.githubusercontent.com/41907215/58331276-a697b180-7e30-11e9-974b-4e00da8750d0.png)

**Comment by thewilkybarkid** [comment]
Thanks @chugginselifesciences.

Think only question is about the logo size:

> * A container for the logo would therefore be 70px tall. _I think it makes sense to add some padding to this to prevent other journal logos filling the entire available space_
> * The libero logo should be 28px wide x 36px tall - so 22px top and bottom padding within the 70px container

To clarify, the default Libero logo is smaller than any custom logo?

**Comment by chugginselifesciences** [comment]
I'm just trying to allow some flexibility in the size of other journal's logos. I don't want to constrain the container to the size of the Libero logo in case other journals need larger logos or provide something with white space around it. I don't think we're ready to define the guidelines to other journals yet, so I made sure we have a large enough container, and can add padding or fixed size to any logo within it, which would then be centered.

Custom logos will liekly need some padding or max-sizes added to look right. I don't think it's possible to ensure all logos in the future are exactly the same size. I included IJM as an example where it wouldn't look right with the same padding as the Libero logo.

**Comment by thewilkybarkid** [comment]
Ok, sounds like it should just be configuration for now. (Can always add whitespace to the image itself too, which is always a bit hacky but 🤷‍♂.)

**Comment by thewilkybarkid** [comment]
Working on styling fixes in https://github.com/libero/pattern-library/pull/103.

**Comment by thewilkybarkid** [comment]
> Below 730px the following should apply:
> 
> [...]
> * 18px from left edge

@chugginselifesciences Just to double-check, it's definitely _not_ set by the grid on smaller screens?

**Comment by chugginselifesciences** [comment]
@thewilkybarkid No, the 24px margin defined by the grid is a bit too large for the header based on its height. The space around the logo becomes unbalanced without increasing the header height.

The current eLife journal has much tighter spacing due the smaller height and smaller logo, which makes sense when there's two header rows. The logo is 6px from the left edge and the menu is 12px. I assume this is not set by the grid.

![image](https://user-images.githubusercontent.com/41907215/58620326-babf3100-82be-11e9-87ae-e4178786819b.png)

For a single row header/menu, I've suggested a taller header, which would feel too cramped if we kept the 6px or 12px space from the screen edges. 24px is a bit too large without increasing the height.

If we're already in a position where, with different languages, the MVP will have to move to a 2 row header like the current journal then we will have to review this. 

![image](https://user-images.githubusercontent.com/41907215/58620961-3a013480-82c0-11e9-9e25-ba54eaae5843.png)

**Comment by chugginselifesciences** [comment]
Looks like I was incorrect, and below 480px the grid margin (wrapper) is 7% not 24px. But still remains that the header should not be set by the grid.

**Comment by davidcmoulton** [comment]
@chugginselifesciences I may be misunderstanding terminology here, but I'm not sure getting the grid to supply the space left of the logo image is going to work that well between 730px up to 1114px. From 1114px and wider the max-width kicks in so that's okay, but below that the logo will be pushed in so far you'll loose a lot of site header real estate and it might look unbalanced once there's a menu in there too. We could give the site header its own grid, but that seems like overkill, at the moment anyway when there's only one putative row of menu items. Perhaps a `vw` left padding on the image between 730 and 1114px would be enough?

This is how it looks at the moment at 796px width with no left space at all. Putting it on the grid would push it in a long way, 
<img width="805" alt="Screenshot 2019-05-30 15 50 38" src="https://user-images.githubusercontent.com/2893480/58641239-b90f6080-82f2-11e9-8a1e-69ded078d8cb.png">

By comparison, eLife's logo is neither on the grid nor flush left. But perhaps I'm misunderstanding what you mean by "grid".
<img width="798" alt="Screenshot 2019-05-30 15 54 06" src="https://user-images.githubusercontent.com/2893480/58641510-405cd400-82f3-11e9-85cd-a92ac00e89b2.png">

**Comment by chugginselifesciences** [comment]
@davidcmoulton I see what you mean. I must have got things confused with xPub's breakpoints so please ignore any suggestion of being set/defined by "the grid". I got confused because on eLife's journal we change the logo at 730px breakpoint. But above 730px it's still defined by fixed px sizes.

I'd like to check I understand how it works on current eLife journal site - please correct me if I'm wrong here.

In eLife's journal the header padding is never defined by percentage. It simply has some fixed px margins/padding to define space between header content and screen edge, and the header has a max width of 1114px. The margin/padding for the logo is partly defined by the image/SVG, and partly by `float: right` within a container fixed at 170px wide (above 730px breakpoint). This means it appears to be 22px from the left edge up to the max header width of 1114px.

![image](https://user-images.githubusercontent.com/41907215/58643959-3b4e5380-82f8-11e9-8cef-ae07a9431e4e.png)

Above a screen width of 1114px the max width of the header means there's more space between logo and screen edge. 

![image](https://user-images.githubusercontent.com/41907215/58644256-d0e9e300-82f8-11e9-884b-4776ede6ce7e.png)

Below 730px we change the logo and move it to just the top row

![image](https://user-images.githubusercontent.com/41907215/58644811-f3303080-82f9-11e9-8762-21270dc5eea8.png)



<br/>


For Libero and the single row toolbar I have been hoping we can change the height of the header when we change the logo size at 730px for a similar mobile/desktop logo size change.

So the header height at 730px and below = 60px. Above 730px wide the header height = 96px


So at 730px and below, to work with the 60px tall header, the logo = 18px x 24px and is 18px from the left edge. 

![image](https://user-images.githubusercontent.com/41907215/58644668-a8aeb400-82f9-11e9-83ed-c86259174cf4.png)


Above 730px the logo is increased to 28px x 36px and the header height = 96px:

![image](https://user-images.githubusercontent.com/41907215/58645344-190a0500-82fb-11e9-99bf-4c3c12b33776.png)


When the header reaches 1114px wide it is centered and the 36px from the header/container edge is still 36px. Any additional space between logo and screen edge is because the header width maxed out.

However, I think the logo looks much better aligned to the content below which also reaches a max width of 1114px. I think the closest breakpoint is 1200px. So I think above 1200px we should remove the 36px margin on the logo (or padding on parent...) so that the logo is aligned with content below:

![image](https://user-images.githubusercontent.com/41907215/58645754-db59ac00-82fb-11e9-8c09-69ed689cd85f.png)



So my suggestion is :

**730px and below:** header height = 60px, logo = 18px by 24px and padding = 18px

**above 730px up to 1200px:** header height = 96px, logo = 28px by 36px and padding = 36px

**above 1200px**: we lose the left padding/margin to align with content below.

**Comment by davidcmoulton** [comment]
> The margin/padding for the logo is partly defined by the image/SVG, and partly by float: right within a container fixed at 170px wide (above 730px breakpoint)

Almost. It's `float: left` with some right hand padding.

I'll implement to verify, but your suggestion looks spot on.

**Comment by davidcmoulton** [comment]
Implemented, works well with the Libero logo:

<img width="409" alt="Screenshot 2019-05-31 09 53 16" src="https://user-images.githubusercontent.com/2893480/58694010-f410a300-8389-11e9-8e46-be4bf9af9818.png">

<img width="749" alt="Screenshot 2019-05-31 09 52 57" src="https://user-images.githubusercontent.com/2893480/58694030-012d9200-838a-11e9-8a82-4490ecab6c4c.png">

<img width="1215" alt="Screenshot 2019-05-31 09 52 29" src="https://user-images.githubusercontent.com/2893480/58694056-0d195400-838a-11e9-8abc-d24455c7b124.png">

**Comment by davidcmoulton** [comment]
Pattern library PR for layout update above: https://github.com/libero/pattern-library/pull/105

**Comment by davidcmoulton** [comment]
@chugginselifesciences Is it okay if the grey vertical bar only appears when there's a menu, i.e. doesn't show up if there's a logo and no menu (if that's even possible)? <img width="374" alt="Screenshot 2019-06-05 15 23 04" src="https://user-images.githubusercontent.com/2893480/58966625-8827a380-87aa-11e9-8012-5c4174abaa67.png">

**Comment by chugginselifesciences** [comment]
@davidcmoulton Yes it would be ideal if the grey separator is only visible when there is a menu. Thanks
