### ISSUE TITLE
Add article PDFs

### ISSUE THREAD

**Issue by thewilkybarkid** [libero/libero#144]
Add a link to download 

<img width="121" alt="Screenshot 2019-05-06 at 15 08 54" src="https://user-images.githubusercontent.com/1784740/57230775-07da1b00-7011-11e9-8307-aa0a6a0e7b6b.png">

## Tasks

- [x] Content Store makes the PDF available.
- [x] Add download icon to the content header pattern. (https://github.com/libero/pattern-library/pull/98)
- [x] Add JATS support (https://github.com/libero/jats-support/pull/14)
- [x] Added to Browser (https://github.com/libero/browser/pull/88)
  - ~[ ] The file downloads rather than opening in the browser~
- [x] Add to the unstable environment (https://github.com/libero/sample-configuration/pull/55)

## Notes

- I'm not separating the template and styles as this is small.
- No menu, the download icon triggers the download.
- JATS to read:
  ```XML
  <article>
    <front>
      <article-meta>
        <self-uri content-type="pdf" xlink:href="[something]"/>
      </article-meta>
    </front>
  </article>
  ```
  taking `@xml:base` into account (must be an absolute URI).

## Related

- Depends on #132 for the Content Store being able to handle assets.

Related to https://github.com/libero/libero/issues/150

**Comment by davidcmoulton** [comment]
Pattern library PR: libero/pattern-library#98

**Comment by thewilkybarkid** [comment]
> The file downloads rather than opening in the browser

One for later (as it's not that simple, have to proxy the request to the asset to add a header on the response).
