### ISSUE TITLE
Add list of authors and affilitations to the content header

### ISSUE THREAD

**Issue by thewilkybarkid** [libero/libero#145]
Add an unstyled list of author names and affiliations (both simple strings) to the content header pattern.

## Tasks

- [x] Add to content header (https://github.com/libero/pattern-library/pull/108)
  - [x] List of author names
  - [x] List of affiliations
- [x] Add JATS support (https://github.com/libero/jats-support/pull/13)
- [x] Add to Browser (https://github.com/libero/browser/pull/87)
  - [x] Author names
  - [x] Institution names
- [x] Add to the unstable environment (https://github.com/libero/sample-configuration/pull/54)

## Notes

- Only covers individual authors (no groups etc).
- No corresponding author icon etc.
- JATS to read:
  ```xml
  <article>
    <front>
      <article-meta>
        <contrib-group>
          <contrib contrib-type="author">
            <name>[..]</name>
            <aff>[string]</aff>
          </contrib>
          [..]
        </contrib-group>
        [..]
      </article-meta>
    </front>
  </article>
  ```
- `@name-style` needs to be read.
- Each `<contrib>` may have many `<aff>`, or none.

## Related

- Blocks #146 (add styling).
- Blocks #162 (add behaviour).

**Comment by davidcmoulton** [comment]
PR: https://github.com/libero/pattern-library/pull/108
