### ISSUE TITLE
Style list of authors and affiliations

### ISSUE THREAD

**Issue by thewilkybarkid** [libero/libero#146]
<img width="788" alt="Screenshot 2019-05-06 at 15 23 00" src="https://user-images.githubusercontent.com/1784740/57232553-c3e91500-7014-11e9-94a2-a805c561cfe4.png">

## Tasks

- [x] Author list styled (https://github.com/libero/pattern-library/pull/110)
- [x] Affiliations list styled (https://github.com/libero/pattern-library/pull/110)
- [x] Browser updated (libero/browser#87)

## Related

- Blocked by #145 (add to template).
- Blocks #162 (add behaviour).

**Comment by davidcmoulton** [comment]
PR: https://github.com/libero/pattern-library/pull/110
