### ISSUE TITLE
Inplement config sharing to Twig layer

### ISSUE THREAD

**Issue by davidcmoulton** [libero/libero#151]
https://github.com/libero/pattern-library/pull/98/files#diff-7bb6b4493ed851122cfb90d0e48aeb98R21 is the first occurrence of configuration, in this case the media statement breakpoint specified in
```
<source srcset="/images/download-full.svg" type="image/svg+xml" media="(min-width: 45.625em)">
```
that is shared between the sass and Twig layers.

### Tasks
- [ ] decide on a suitable data format to export to the Twig layer (documented to this ticket)
- [ ] update [ConfigDistributor.js](https://github.com/libero/pattern-library/blob/master/libero-config/bin/ConfigDistributor.js) to export new format to appropriate location for Twig to access
- [ ] update [config--libero-default.js](https://github.com/libero/pattern-library/blob/master/libero-config/config--libero-default.js#L66) to export to the templating layer
- [ ] Update https://github.com/libero/pattern-library/pull/98/files#diff-7bb6b4493ed851122cfb90d0e48aeb98R21 to use the config-exported value

**Comment by thewilkybarkid** [comment]
Thinking about it, the breakpoint is actually computed by Sass rather than being shared between Twig and Sass. I think this might be a suitable to consider moving the config to Sass, and output values that can be used by the other layers...
