### ISSUE TITLE
Support HTTPS on unstable environment

### ISSUE THREAD

**Issue by giorgiosironi** [libero/libero#158]
## Problem / Motivation
 
- WHO wants this? Service providers
- WHEN and WHERE do they want it? Demonstrated on a publicly available environment
- WHAT do they want? A reference implementation of HTTPS support
- WHY do they want this? As a minimal requirement for publishing platforms to be sold

## Proposed solution

- Use Terraform's ACME provider to automate Let's Encrypt setup and provide a free certificate.

## Tasks

- [x] private key safe storage (can we avoid Terraform state?)
- [x] wildcard investigation
- [ ] ~OCSP stapling~
- [x] DNS CAA
- [ ] ~HSTS~
- [ ] ~HPKP~
- [x] storage of certificates in `environments`
- [x] nginx configuration
- [x] redirects in nginx from HTTP to HTTPS

## Clarification needed and assumptions

- A question
- An assumption

**Comment by giorgiosironi** [comment]
In theory, Let's Encrypt now supports [wildcard certificates](https://community.letsencrypt.org/t/acme-v2-production-environment-wildcards/55578).

**Comment by giorgiosironi** [comment]
It seems that in the [suggested setup](https://www.terraform.io/docs/providers/acme/index.html) the private key and the certificate are all stored unencrypted in Terraform's state. Would like to provide a private key protected by `git-crypt` instead.

**Comment by giorgiosironi** [comment]
Note from https://letsencrypt.org/docs/faq/ that Let's Encrypt supports Domain Validation certificates, not Organization Validation or Extended Validation ones. The certificates we use at eLife (Gandi or Fastly issued) are all just Domain Validation ones as far as I know.

**Comment by giorgiosironi** [comment]
Wondering if we can [store fewer private keys in the Terraform state](https://github.com/terraform-providers/terraform-provider-acme/issues/70).

**Comment by giorgiosironi** [comment]
Identified that attempting to create a wildcard certificate runs into:
```
1 error occurred:
        * acme_certificate.certificate: 1 error occurred:
        * acme_certificate.certificate: error creating certificate: acme: Error -> One or more domains had a problem:
[*.libero.pub] acme: error: 404 :: POST :: https://acme-staging-v02.api.letsencrypt.org/acme/authz/238306 :: urn:ietf:params:acme:error:malformed :: No such authorization,
 url: 
```
Not sure yet what this means, probably related to the different DNS challenge to be created.

**Comment by giorgiosironi** [comment]
`TF_LOG=TRACE` doesn't help as it doesn't show the (malformed?) body of the failed request.

**Comment by giorgiosironi** [comment]
Seems like the [`infrastructure` build](https://travis-ci.com/libero/infrastructure/builds/116145198) has some problem with the encrypted files?

**Comment by giorgiosironi** [comment]
Need to setup `git-crypt` for Travis CI there, which had never been needed until now.

**Comment by giorgiosironi** [comment]
Various pull requests open at the moment, works locally for one container.

**Comment by giorgiosironi** [comment]
Kinda running but on the wrong port, `curl -k -v https://localhost:8443` succeeds.

**Comment by giorgiosironi** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=unstable.libero.pub&hideResults=on shows an `A` with the option to implement CAA DNS, which should be simple.

**Comment by thewilkybarkid** [comment]
Meant to be closed? Still in doing, some checkboxes not entirely removed.

**Comment by giorgiosironi** [comment]
Yes closed, needs to be moved manually probably. The checkboxes are ~strikethrough~ due to being out of scope for demo environment e.g. public key pinning.

**Comment by thewilkybarkid** [comment]
(Prefer striking through the checkbox itself.)
