### ISSUE TITLE
Create "demo" environment

### ISSUE THREAD

**Issue by giorgiosironi** [libero/libero#166]
`demo.libero.pub` and similar URLs.

## Problem / Motivation
 
- WHO wants this? The marketing team
- WHEN and WHERE do they want it? Before July 10th, as soon as possible
- WHAT do they want? An environment with stricter uptime requirements 
- WHY do they want this? To give out the URL in press releases for external people to use.

## Tasks

- [x] Create new instance of Terraform state in `infrastructure` called `demo`
- [x] Parameterize `sample-configuration` to work with multiple environments
- [x] Deploy to `unstable` and `demo` from `environments`
- [x] Document and test release process with tags
~- [ ] Investigate 0-downtime deployment~

## Clarification needed and assumptions
- How often should we deploy to `demo`? Just after `unstable` and its (smoke) tests have passed, or with a lower cadence (daily, weekly)?
- Containers should not be turned off during deploy, to avoid downtime
- We are still going to deploy to a single node as that's what `sample-configuration` supports

**Comment by thewilkybarkid** [comment]
> * How often should we deploy to `demo`? Just after `unstable` and its (smoke) tests have passed, or with a lower cadence (daily, weekly)?

Probably needs to be stable, so without forcing controlled changes everywhere yet, make it manual?

**Comment by giorgiosironi** [comment]
> make it manual?

Sounds like a `deploy` to trigger only on certain tags of `environments`. Yet those tags should include a set of versions rather than just `latest` for everything, to be reproducible.

**Comment by giorgiosironi** [comment]
https://demo.libero.pub/ is there, with just the fixture content, using the linked PRs. Everything ready for review.

**Comment by giorgiosironi** [comment]
https://travis-ci.com/libero/environments/requests helps debugging when builds don't start:
```
Branch "latest/20190629" not included per configuration. 
```

**Comment by giorgiosironi** [comment]
https://travis-ci.com/libero/environments/builds/117178279 seems to have deployed on `demo` now.

**Comment by giorgiosironi** [comment]
https://travis-ci.com/libero/infrastructure/builds/117312485 is a similar tag-based build for `demo`.
