### ISSUE TITLE
Deploy browser to the unstable environment

### ISSUE THREAD

**Issue by giorgiosironi** [libero/libero#22]
## Problem / Motivation
 
- WHO wants this? Developers and product managers
- WHEN and WHERE do they want it? Available on a public URL accessible from any browser
- WHAT do they want? A running instance of Libero default services, with sample data, running the latest available versions
- WHY do they want this? To demonstrate features from the current milestone

## Proposed solution

Use an isolated AWS account to provide a running version of all components, in their default version and configuration.

## Tasks

- [x] Build a `browser` image
- [x] Push a `browser` image
- [x] Find out how we can have private Github repositories (or somewhere else) for credentials
- [x] [Setup a Terraform repository for the infrastructure (EC2)](https://github.com/libero/libero/issues/28)
- [x] Setup an `environments` repository to deploy new versions of browser
- [x] Setup a `sample-configuration` for `docker-compose`
- [x] Trigger configuration repository builds
- [x] Add DNS
- [x] Add provisioning of `git`, `docker`, `docker-compose`
- [x] Change AMI to something that does not continue to start (and crash) `ecs-agent`
- [x] Check if build outputs are still empty or it was a transient problem
- [x] Write some documentation in [infrastructure](https://github.com/libero/infrastructure/)
- [x] Remember to delete https://console.aws.amazon.com/route53/home?#resource-record-sets:ZXITH0J8EA6WB (old hosted zone from eLife AWS account)

## Clarification needed and assumptions

- Developers will be able to maintain the separate docker-compose configuration.
- The contract between services and towards their infrastructure is stable enough to avoid frequent breakages or synchronized deployment.

## Technical notes

Deploy onto a EC2 instance for an isolated AWS account (or equivalent VM in another cloud). Account can use consolidated billing sponsored by eLife.

Use (or re-use) a docker-compose configuration to easily port the "single laptop" setup onto the cloud (not native but easy to maintain.)

## User interface

Intended URL: https://unstable.libero.pub

![libero-continuous-deployment](https://user-images.githubusercontent.com/160299/44035426-63ee58d8-9f07-11e8-8989-c54311dffc36.jpg)

**Comment by thewilkybarkid** [comment]
Going to need a bunch of accessible things:

- Web app
- Dashboard
- API

All under https://unstable.libero.pub? (eg https://unstable.libero.pub/dashboard)

**Comment by elrossco22** [comment]
Can we not store the credentials in Travis CI rather than GH, this has the capability to obfuscate during the build ?

**Comment by elrossco22** [comment]
The Terraform statefile should be stored somewhere globally, In the past we used an S3 bucket for this. However other file storage options are available

**Comment by elrossco22** [comment]
Can the `Journal` folder within the walking skeleton repository be taken from master as a vertical slice for this and id so, what semantic version number should this be ?

**Comment by giorgiosironi** [comment]
> Going to need a bunch of accessible things: Web app/Dashboard/API

`/component` suffixes assume a single proxying layer, but in the context of an environment backed by a single machine this should be fine

**Comment by giorgiosironi** [comment]
> Can we not store the credentials in Travis CI rather than GH, this has the capability to obfuscate during the build ?

Does https://docs.travis-ci.com/user/encryption-keys/ cut it? `git-crypt`?

> The Terraform statefile should be stored somewhere globally, In the past we used an S3 bucket for this. However other file storage options are available

:+1: simple enough if the deployment is on AWS

> Can the Journal folder within the walking skeleton repository be taken from master as a vertical slice for this and id so, what semantic version number should this be ?

I think we are going to target the new sliced repo directly, rather than the existing walking skeleton

**Comment by elrossco22** [comment]
@giorgiosironi I was more thinking 
https://docs.travis-ci.com/user/environment-variables/#defining-variables-in-repository-settings

**Comment by giorgiosironi** [comment]
> https://docs.travis-ci.com/user/environment-variables/#defining-variables-in-repository-settings

Scales well for a few repositories that have to build and push Docker images

**Comment by giorgiosironi** [comment]
First step: finding out how to host private Git repositories for credentials. Long story short, this part may be provided by the https://github.com/elifesciences/ organization until we sort it out here.

**Comment by giorgiosironi** [comment]
Set up `DOCKER_*` variables at https://travis-ci.com/libero/content-store/settings

**Comment by giorgiosironi** [comment]
Running and failing as expected because the EC2 instance is not there yet: https://travis-ci.com/libero/environments/builds/83035039

**Comment by giorgiosironi** [comment]
Both in review:

- https://github.com/libero/infrastructure/pull/2
- https://github.com/libero/environments/pull/2

**Comment by giorgiosironi** [comment]
https://travis-ci.com/libero/environments build failed because of SSH key checking, need to use `StrictHostKeyChecking` (maybe also on `scp` commands, not sure if the first command is the only one needing it).

**Comment by giorgiosironi** [comment]
The orchestration is able to log in into the server, but there is a runaway process (ncontinuing to be restarted) consuming resources that made the Docker daemon crash and freeze the instance. Need to remove it:
```
CONTAINER ID        IMAGE                            COMMAND             CREATED             STATUS                  PORTS               NAMES
dae2c68db666        amazon/amazon-ecs-agent:latest   "/agent"            1 second ago        Up Less than a second                       ecs-agent
```

**Comment by giorgiosironi** [comment]
Also port 80 seems to be allocated by too many processes:
```
ERROR: for 6754170b4b6c_sample-configuration_web_1  Cannot start service web: driver failed programming external connectivity on endpoint sample-configuration_web_1 (e7ffcd5a9beb5e69e63d0d4352a6f979aad8abe911fefd91bd763703c79be2e5): Bind for 0.0.0.0:80 failed: port is already allocated
```
It was a `docker-proxy`, but difficult to know proxying to which container.

**Comment by giorgiosironi** [comment]
First [green build](https://travis-ci.com/libero/environments/jobs/146136186#L414) but doesn't feel very stable; will continue on simplifying the instance.

**Comment by giorgiosironi** [comment]
https://github.com/libero/infrastructure/pull/3 simplifies the AMI, using half of the RAM that was used before for the base OS.

**Comment by giorgiosironi** [comment]
Will create a `libero-travis` Github user, to authenticate into Travis CI and generate an API token. This token can be then used to trigger the `environments` build from the `browser` build:
https://docs.travis-ci.com/user/triggering-builds/

**Comment by giorgiosironi** [comment]
https://github.com/libero/browser/pull/14 for the trigger.

**Comment by giorgiosironi** [comment]
Requested transfer of `libero.pub` to the right AWS account in:
https://console.aws.amazon.com/support/v1#/case/?displayId=5370286141&language=en

**Comment by giorgiosironi** [comment]
For some more documentation:

- https://github.com/libero/infrastructure/pull/4
https://github.com/libero/environments/pull/3

**Comment by giorgiosironi** [comment]
https://travis-ci.com/libero/environments/builds/85159785 triggered by https://travis-ci.com/libero/browser/builds/85159430 and green.

**Comment by giorgiosironi** [comment]
Waiting for DNS transfer to add it to `infrastructure`. For comments on the documentation, but will merge them when there's nothing else remaining.

**Comment by giorgiosironi** [comment]
https://github.com/libero/infrastructure/pull/5 makes http://unstable.libero.pub/articles/42 work.

**Comment by giorgiosironi** [comment]
Both `libero.pub` and `libero.website` Route 53 Hosted Zones now at https://console.aws.amazon.com/route53/home?#Dashboard: for the Libero AWS account.
