### ISSUE TITLE
Deploy dummy-api to unstable environment

### ISSUE THREAD

**Issue by giorgiosironi** [libero/libero#23]
## Problem / Motivation
 
- WHO wants this? Developers and product managers
- WHEN and WHERE do they want it? Available on a public URL accessible from any browser
- WHAT do they want? Some content added to the unstable environment
- WHY do they want this? To demonstrate and test features from the current milestone on many content samples

## Proposed solution

Deploy a [`dummy-api`](https://github.com/libero/dummy-api) to the `unstable` environment to allow usage of test data from the corresponding `browser`.

## Tasks

- [x] Build a `dummy-api` image
- [x] Push a `dummy-api` image
- [x] Add `dummy-api` to `sample-configuration` repository
- [x] Add `dummy-api` knowledge to `environments` repository
- [x] Trigger `environments` pipeline on `dummy-api` new images through `deploy` phase
- [x] Add `HEALTHCHECK` to `dummy-api`
- [x] Add `HEALTHCHECK` to `browser`
- [x] Add some smoke tests after deploy
- [x] Make smoke tests wait for container readiness
- [x] Try to get the `libero` Docker Hub namespace
- [x] Add `unstable--dummy-api.elifesciences.org` DNS
- [x] Integrate `browser` favicon into `sample-configuration` setup
- [x] Add data to `dummy-api` and configuration to `browser`
- [x] Everything should be green and ~`unstable.libero.pub/article/42`~ http://unstable.libero.pub/articles/article1 should be loading

## Clarification needed and assumptions

- At least a dummy implementation of backend services is necessary to be able to use all features in the unstable environment.

## Technical notes

See https://github.com/libero/libero/issues/22

## User interface / Wireframes

Possible public URL: https://dummy-api.unstable.libero.pub

**Comment by giorgiosironi** [comment]
Renamed to reflect that we are deploying `dummy-api`.

**Comment by thewilkybarkid** [comment]
@stephenwf Would be interested to know if you have any suggestions for the container config (eg FPM optimisation). Not a blocker for this though.

**Comment by giorgiosironi** [comment]
`Thank you for contacting Docker Support! Your request 00062637 has been submitted and a Support Engineer will be contacting you during business hours (Monday-Friday, 9:00am - 6:00pm local time).`

**Comment by giorgiosironi** [comment]
https://github.com/libero/sample-configuration/pull/4 tries to put everything (`nginx`, `php-fpm`, multiple services) together.

**Comment by giorgiosironi** [comment]
Main part is done, cleanup remains:
```
$ curl -v http://unstable--dummy-api.libero.pub/ping
*   Trying 34.238.193.238...
* Connected to unstable--dummy-api.libero.pub (34.238.193.238) port 80 (#0)
> GET /ping HTTP/1.1
> Host: unstable--dummy-api.libero.pub
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: nginx/1.15.2
< Content-Type: text/plain; charset=utf-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Cache-Control: must-revalidate, no-store, private
< Date: Fri, 16 Nov 2018 15:48:36 GMT
< 
pong
```

**Comment by giorgiosironi** [comment]
Smoke tests unstable in https://travis-ci.com/libero/environments/builds/91686972
It's a case of waiting for the `nginx` port to be opened and for the `fpm` containers to start. We may get away with some `exec` commands for now, but we'll need to get to containers declaring their health state so that smoke tests (and orchestrators, monitoring, etc) can target that status, agnostically.

**Comment by giorgiosironi** [comment]
After trying to use `timeout docker-compose` with the `nc` inside the `fpm` containers and failing at it, I'd like to delegate all this looping to `HEALTHCHECK`.

**Comment by giorgiosironi** [comment]
https://github.com/libero/dummy-api/pull/11 as the next logical step, all while trying to limit duplication across repositories.

**Comment by giorgiosironi** [comment]
https://github.com/libero/sample-configuration/pull/6 for the shared "pod" volume setup.

**Comment by giorgiosironi** [comment]
A bit unrelated but spawned from this:

- https://github.com/libero/scripts/pull/1
- https://github.com/libero/dummy-api/pull/12

**Comment by giorgiosironi** [comment]
https://github.com/libero/environments/pull/12 is the latest in trying to fix the pipelines before we add data.

**Comment by giorgiosironi** [comment]
https://github.com/libero/sample-configuration/pull/10 will add some data.

**Comment by stephenwf** [comment]
@thewilkybarkid @giorgiosironi For the `HEALTHCHECK` in fpm, you could configure the [built-in](https://easyengine.io/tutorials/php/fpm-status-page/) `/ping` endpoint, it should get you a healthy status quicker than hitting the root, which would be blocked by the PHP application itself (not blocking nginx connecting).

**Comment by giorgiosironi** [comment]
https://travis-ci.com/libero/environments/builds/92517437 deployed the dummy data, but http://unstable.libero.pub/articles/42 is a 500, taking a look.

**Comment by giorgiosironi** [comment]
```
browser_fpm_1    | [26-Nov-2018 10:03:55] WARNING: [pool www] child 7 said into stderr: "[2018-11-26 10:03:55] request.INFO: Matched route "libero.content.scholarly_article.item". {"route":"libero.content.scholarly_article.item","route_parameters":{"_route":"libero.content.scholarly_article.item","_controller":"libero.content_page.controller.content.scholarly_article","id":"42"},"request_uri":"http://unstable.libero.pub/articles/42","method":"GET"} []"
browser_fpm_1    | [26-Nov-2018 10:03:55] WARNING: [pool www] child 7 said into stderr: "[2018-11-26 10:03:55] request.CRITICAL: Uncaught PHP Exception GuzzleHttp\Exception\ClientException: "Client error: `GET http://web:1080/scholarly-articles/items/42/versions/latest` resulted in a `404 Not Found` response: <?xml version="1.0" encoding="UTF-8"?> <problem xmlns="urn:ietf:rfc:7807" xml:lang="en"><status>404</status><title>Item  (truncated...) " at /app/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php line 113 {"exception":"[object] (GuzzleHttp\\Exception\\ClientException(code: 404): Client error: `GET http://web:1080/scholarly-articles/items/42/versions/latest` resulted in a `404 Not Found` response:\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<problem xmlns=\"urn:ietf:rfc:7807\" xml:lang=\"en\"><status>404</status><title>Item  (truncated...)\n at /app/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113)"} []"
browser_fpm_1    | 172.30.0.4 -  26/Nov/2018:10:03:55 +0000 "GET /index.php" 500
```

**Comment by thewilkybarkid** [comment]
There’s no error handling yet, but that’s right. Correct ID is working.

**Comment by giorgiosironi** [comment]
http://unstable.libero.pub/articles/article1 is the right one.

**Comment by giorgiosironi** [comment]
Also http://unstable.libero.pub/blog/post1
