### ISSUE TITLE
Subject label on page

### ISSUE THREAD

**Issue by Maelplaine** [libero/libero#3]
## Problem / Motivation
 
- WHO reader
- WHEN landing on an article page
- WHERE article header 
- WHAT they want to know what is the subject area or category of the article 
- WHY because readers might be interested in finding more articles with the same label.

## Proposed solution and tasks

- Subject has the same format as eLife's journal and is located above the title
- Isn't linking to the page with all the articles with the same type of articles for now, the search functionality will be required

## Tasks:
- [ ] Configuration of subjects and readable names in the article store
- [ ] Article store storing this information ([0..N] subjects) per each article, but not necessarily indexing it
- [ ] Schema extension if not already present
- [x] Journal rendering subjects

## Clarification needed and assumptions
- Can we use ‘Subject’ as a generic term for all the journals? eLife uses MSA, subject and research category depending on who you’re talking to: https://github.com/libero/libero/wiki/Ubiquitous-Language-Thesaurus
> IJM happy to use MSA or Subject Area
- Subject area is a fixed list
> Yes (eLife, IJM, RSC, Hindawi) 
> Not in the XML for RSC and Hindawi
- What is IJM’s list of subject areas? Is the list in the kitchen sink XML accurate
> Yes IJM confirmed that it is accurate
- List: Health, Demography, Education, Labour supply and demand, Social protection, Retirement, Small area estimation, Environment, Transport, Micro-macro links, Finance, Savings and wealth, Housing, Innovation, Institutions and incentives, Methodology, Miscellaneous
(taken from https://github.com/microsimulation/ijm-xml/blob/master/ijm-00666.xml)

## Technical notes
/article/front/article-meta/article-categories/subj-group[@subj-group-type=’heading’]/subject appears to be the subject values

## User interface / Wireframes

![image](https://user-images.githubusercontent.com/39725642/43323131-ad563dd6-91a8-11e8-8613-718b4688a187.png)

**Comment by thewilkybarkid** [comment]
Having a basic approach working in Browser, waiting for the existing PRs there to close before opening.

**Comment by nlisgo** [comment]
Three of the todo's should be split out into separate tickets. This ticket should just cover the work on `pattern-library` and `browser`.
