### ISSUE TITLE
Establish pattern library's styling base

### ISSUE THREAD

**Issue by davidcmoulton** [libero/libero#39]
## Problem / Motivation
To provide a stable style base from which to build out the patterns.

## Proposed solution
Establish necessary sass variables, and provide css to normalise styles. Set up typographical hierarchy in code, based on eLife's journal style.

## Tasks
- [ ] setup normalised styles
- [ ] setup initial element-level styles
- [ ] setup typographical hierarchy

## Clarification needed and assumptions
Assumes Libero styles can be based on eLife styles.
