### ISSUE TITLE
Create governance page on libero.pub

### ISSUE THREAD

**Issue by BlueReZZ** [libero/libero#44]
## Problem / Motivation
 
- WHO wants this?
The community, particularly those involved in governance discussions
- WHEN and WHERE do they want it?
On a public facing website with a long-lasting, short and discoverable link, so https://libero.pub/governance/
- WHAT do they want?
A simple HTML page, that looks like it is part of the eLife family of websites containing the text from the [governance document in the Libero Team Drive](https://docs.google.com/document/d/15UGWSArpShWZdePyV2RPo7J4cjyGidfcGt6pkUnwhQY)
- WHY do they want this?
They would like to publicise and be transparent about the agreed governance model
## Proposed solution

- A plain HTML page commited to master in https://github.com/libero/libero.github.io should appear at https://libero.pub/governance/
- Import the pattern CSS manually to start with and try and automate later

## Tasks

- [x] Create HTML from the source document
- [x] Use patterns from the pattern library
- [x] Merge into master on https://github.com/libero/libero.github.io which makes it live
 
## Clarification needed and assumptions

- Should the patterns come from eLife or Libero pattern library? We could use eLife for expediency but Libero would make more sense in the future.
- Assumption: it should look like an eLife page

## Technical notes
- This is also a trial of github pages and the related workflow - does it work for us?

**Comment by discodavey** [comment]
https://github.com/libero/libero.github.io/pull/4

**Comment by BlueReZZ** [comment]
Merged, now live at https://libero.pub/governance/ will follow up with issues for additional pages
