### ISSUE TITLE
Implement config usable across sass, js and templating

### ISSUE THREAD

**Issue by davidcmoulton** [libero/libero#50]
## Problem / Motivation
As a developer working on or implementing the Libero frontend, I want a single source of truth for common properties used across different parts of the codebase, in order to make it easier to maintain and reason about.

## Proposed solution
- Use a json config object to populate respective sass & js configurations at build time.
- Start with breakpoints for PoC as these are likely used in js as well as sass.
- Extend as necessary.

## Tasks
- [ ] Decide on a config format.
- [ ] Incorporate config data into sass.
- [ ] Incorporate config data into PoC js.
- [ ] Automate incorporation into sass & js via build pipeline.

**Comment by davidcmoulton** [comment]
Initial stab at something at https://github.com/libero/patterns-core/pull/17

**Comment by davidcmoulton** [comment]
Unchecked the checklist items as reevaluated approach means this needs to be done in a more loosely coupled fashion.
