### ISSUE TITLE
Add a Code of Conduct for Libero

### ISSUE THREAD

**Issue by BlueReZZ** [libero/libero#57]
## Problem / Motivation
 
- WHO the community
- WHEN before the press release on the new governance structure is publicised w/c 29th Oct 2018 WHERE in CODE_OF_CONDUCT.md in all repos
- WHAT a single place for a code of conduct and links to that from all other repos
- WHY to encourage the behaviour we want to see in the world :https://opensource.guide/code-of-conduct/

## Proposed solution

- Use the [Contributor Covenant](https://www.contributor-covenant.org/) with a summary of the reporting/enforcement procedure in the https://github.com/libero/community/ repo's `CODE_OF_CONDUCT.md`
- Add a redirection to https://libero.pub/code-of-conduct/ to the community repo code of conduct
- Add a `CODE_OF_CONDUCT.md` to all other repos in the `libero` organisation containing the text defined below

## Tasks

- [x] Add code of conduct to `libero/community` (https://github.com/libero/community/pull/17) 
- [x] Add redirection (https://github.com/libero/libero.github.io/pull/9)
- [x] Add code of conduct to all other repos

## Clarification needed and assumptions

- Contributor Covenant has been agreed by the community in Slack

## User interface / Wireframes

```markdown
# Libero Community Code of Conduct
The community has elected to adopt the Contributor Convenant in order to foster an open and
welcoming environment where contributors can feel safe to make contributions in any way they wish. 

The full text of the code of conduct is available at https://libero.pub/code-of-conduct/ along with details on how to report any instances of abusive, harassing, or otherwise unacceptable behaviour.
```

**Comment by BlueReZZ** [comment]
Added PR for redirection, just needs approving: https://github.com/libero/libero.github.io/pull/9

Once this is merged, the final task can be done on all repos starting with updating this WIP PR: https://github.com/libero/patterns-core/pull/6

**Comment by thewilkybarkid** [comment]
Will merge, but wondering why `libero/community` has `develop` and `master` branches? /cc @giorgiosironi

**Comment by giorgiosironi** [comment]
Not sure but there's no release or deploy involved so `master` should suffice?

**Comment by davidcmoulton** [comment]
The code of conduct file is not registering in https://github.com/libero/php-coding-standard/community I've contacted GitHub to ask if there's anything else we need to do to get the green tick. Waiting to hear back.

**Comment by davidcmoulton** [comment]
That was quick! From GitHub:

"We've received a few reports of users encountering this, and have opened an internal issue for our team to investigate.

I can't offer an ETA on a fix, but will let you know as soon as we have any news to share."

**Comment by davidcmoulton** [comment]
I've raised pull requests against the Libero repos still requiring `CODE_OF_CONDUCT.md` files. Where the repo's readme has a "Getting" help" section, I've added a link to the code of conduct there too. Repo owners: please review and merge if you approve the changes.
