### ISSUE TITLE
Create Steering Committee Page on Libero website

### ISSUE THREAD

**Issue by BlueReZZ** [libero/libero#58]
## Problem / Motivation
 
- WHO the community
- WHEN and WHERE at https://libero.pub/governance/steering-committee.html
- WHAT a page detailing the purpose and membership of the steering committee
- WHY to be open and transparent about who influences the governance of Libero

## Proposed solution

- A page similar to the https://libero.pub/governance/ with content from https://docs.google.com/document/d/1wZW-bftYhKxHDHXds2eVVTfTfEXTRJo14Fp-FRkG7vE/edit

## Tasks

- [x] Create page in `libero/libero.github.io`
- [x] Add appropriate link to the governance page https://github.com/libero/libero.github.io/blob/f03fd238e405ab6dd2bb1b69501ebe95d25edc86/governance/index.html#L102
- [x] Update Address in Footer for steering committee and governance page
 
## Clarification needed and assumptions

- Draft document of text and membership is not yet confirmed

**Comment by discodavey** [comment]
https://github.com/libero/libero.github.io/pull/10

**Comment by BlueReZZ** [comment]
Merged
