### ISSUE TITLE
Update links on the governance page

### ISSUE THREAD

**Issue by BlueReZZ** [libero/libero#59]
## Tasks

- [ ] A link to the MOU: [Google Drive Doc](https://docs.google.com/document/d/1AKj5hCEOOckwAMPwiB4mM6i3AAE7aPyOgWm9PSPQJRQ/edit) at [line 121](https://github.com/libero/libero.github.io/blob/f03fd238e405ab6dd2bb1b69501ebe95d25edc86/governance/index.html#L121)
- [ ] A change to the text around CLAs to refer to a single CLA, for entities and individuals, and a link to the CLA: https://libero.pub/governance/cla/ at [line 170](https://github.com/libero/libero.github.io/blob/f03fd238e405ab6dd2bb1b69501ebe95d25edc86/governance/index.html#L170)
- [ ] A link to `CONTRIBUTING.md`: https://github.com/libero/community/CONTRIBUTING.md at [ line 172](https://github.com/libero/libero.github.io/blob/f03fd238e405ab6dd2bb1b69501ebe95d25edc86/governance/index.html#L172)
- [ ] Link `Contributor Convenant` on [line 261](https://github.com/libero/libero.github.io/blob/f03fd238e405ab6dd2bb1b69501ebe95d25edc86/governance/index.html#L261) to https://www.contributor-covenant.org/
- [ ] A link to the code of conduct: https://libero.pub/code-of-conduct/ at [line 267](https://github.com/libero/libero.github.io/blob/f03fd238e405ab6dd2bb1b69501ebe95d25edc86/governance/index.html#L267)

## Clarification needed and assumptions

- The linked files need to be in place before merging this and `CONTRIBUTING.md` is still missing. The code of conduct is awaiting #57

**Comment by BlueReZZ** [comment]
#61 is now complete so the link can be added now

**Comment by discodavey** [comment]
Have added link for Contributing Guide but using https://github.com/libero/community/blob/master/CONTRIBUTING.md as link in task above does not go anywhere.

**Comment by discodavey** [comment]
https://github.com/libero/libero.github.io/pull/12
