### ISSUE TITLE
Update CLA to have an Entity and Individual CLA version

### ISSUE THREAD

**Issue by BlueReZZ** [libero/libero#75]
## Problem / Motivation
 
Split the CLA into two to cater to companies and individuals, because the individual CLA would conflict with most employment contracts, and it's also more convenient for a company to sign up once for all its employees.

## Proposed solution

https://libero.pub/goverance/cla/ should explain and offer a choice of CLAs to contributors from these CLAs generated here: http://contributoragreements.org/u2s/zzhgrdlbw

## Tasks

- [x] Create and style the entity CLA
- [x] Create and style the individual CLA
- [x] Replace text on CLA landing page to offer and explain the choice
- [x] Make the CLAs printable
- [x] Update template for individual CLA in HelloSign (@BlueReZZ has to do this)
- [x] Create a template for entity CLA in HellloSign (@BlueReZZ has to do this)

**Comment by discodavey** [comment]
Added styling and print styles to individual and entity pages

**Comment by BlueReZZ** [comment]
Updated HelloSign. We are limited on the number of "templates" we can have so each Entity CLA will need to be uploaded and sent when required - print web page as PDF, upload as a new doc, add signature areas and send. This probably makes sense for a company to company legal doc anyway.
