### ISSUE TITLE
Add content text

### ISSUE THREAD

**Issue by Maelplaine** [libero/libero#8]
## Problem / Motivation
 
- WHO readers
- WHAT read the text of the articles

## Proposed solution

- Should support from 1 to _n_ number of paragraphs

## Tasks

- [ ] check or expand schema
- [ ] support in article store
- [ ] add a one column CSS grid so that paragraphs are centered (#99)
- [ ] expose in Journal

## Clarification needed and assumptions

- Does this include the abstract?
> For the XML, the abstract and the digest is part of the _front_ whereas the _body_ is made of the sections from Introduction down to Materials and Methods. The _back_ is made of the last sections

## Technical notes
- We could use this technology 
- More notes or suggestions

**Comment by thewilkybarkid** [comment]
Should these include things like bold, emphasis, colours?

**Comment by Maelplaine** [comment]
Yes ideally that would include things like that. We could create another ticket if that would take too much time for you to have them with the text.
