### ISSUE TITLE
Serve pattern-library on unstable environment

### ISSUE THREAD

**Issue by giorgiosironi** [libero/libero#83]
## Problem / Motivation
 
- WHO wants this? Tech, Product (UX)
- WHEN and WHERE do they want it? Available for a demo on 19/12/2018
- WHAT do they want? To see a recent `pattern-library` version at a URL
- WHY do they want this? To show UI patterns in isolation from `browser`

## Tasks

- [x] Publish `liberoadmin/pattern-library:latest` (`ui`) Docker image on Docker Hub (https://github.com/libero/pattern-library/pull/34)
- [x] Add image and configuration to `sample-configuration` (https://github.com/libero/sample-configuration/pull/11)
- [x] Add a `unstable--*.libero.pub` hostname (https://github.com/libero/infrastructure/pull/9)
- [x] Manually deploy a recent version onto `unstable`

**Comment by thewilkybarkid** [comment]
I'd have a preference of `unstable--pattern-library.libero.pub` /cc @davidcmoulton.

**Comment by giorgiosironi** [comment]
Pushed the `liberoadmin/pattern-library:a6b3e031bca862b3266fbc7f3b5e5a7a6c40cdda` image, also with the tag `latest`. Had to authenticate with [`liberoadmin` Docker Hub credentials](https://github.com/elifesciences/it-admin/blob/master/libero.md).

**Comment by giorgiosironi** [comment]
https://travis-ci.com/libero/environments/builds/95119168 deployed http://unstable--pattern-library.libero.pub/ for the first time, the `latest` it is using is not automatically updated.
