### ISSUE TITLE
Automated deployment pipeline for pattern-library

### ISSUE THREAD

**Issue by giorgiosironi** [libero/libero#84]
## Problem / Motivation
 
- WHO wants this? Developers
- WHEN and WHERE do they want it? On each new commit on `master`
- WHAT do they want? For the latest version to flow to the `unstable` environment
- WHY do they want this? To always be able to access and demonstrate the canonical version of the most recent changes

## Tasks
- [x] Verify https://github.com/libero/libero/issues/83 is done
- [x] Introduce [a dynamic tag in `sample-configuration`](https://github.com/libero/sample-configuration/pull/13) corresponding to the `pattern-library`'s version
- [x] Expand `environments` to [update this tag](https://github.com/libero/environments/pull/14)
- [x] [Trigger `environments` as part of `deploy`](https://github.com/libero/pattern-library/pull/41), depends on [submodule](https://github.com/libero/scripts/pull/3)

**Comment by giorgiosironi** [comment]
Tagged @GiancarloFusiello for the reviews, expanding descriptions to give him context.

**Comment by giorgiosironi** [comment]
Tested last task in https://travis-ci.com/libero/pattern-library/builds/98030328 which triggered https://travis-ci.com/libero/environments/builds/98030680
